name: Paintball
description: "A paintball gamemode made for Minecraft: Bedrock Edition"
author: sylvrs
version: 0.7.0
api: [4.0.0]
main: paintball\PaintballBase
commands:
  start:
    description: "Starts the game"
    usage: /start
    permission: pocketmine.group.operator
  createarena:
    description: "Starts the process of creating an arena"
    usage: /createarena
    permission: pocketmine.group.operator
  creategame:
    description: "Creates a new game"
    usage: /creategame
    permission: pocketmine.group.operator
  join:
    description: "Joins the default game"
    usage: /join
    permission: pocketmine.group.user