name: Paintball
description: "A paintball gamemode made for Minecraft: Bedrock Edition"
author: sylvrs
version: 0.0.1
api: [4.0.0]
main: paintball\PaintballBase
commands:
  start:
    description: "Starts the game"
    usage: /start
    permission: pocketmine.group.operator